name: Push to Docker hub
run-name: "Push to docker hub: ${{ github.actor }} 🚀"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Hello
        run: echo $GITHUB_RUN_NUMBER
      - name: Run Makefile
        run: |
          echo make docker publish DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD BUILD_NUMBER=$GITHUB_RUN_NUMBER
      - run: echo "🍏 This job's status is ${{ job.status }}."